<a href="https://colab.research.google.com/github/arunharan/python_class/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1 style="font-size:50px;color:gray;"><center>Introduction to Numpy</center></h1>

![](http://m.memegen.com/o6i6hi.jpg)

# [RESOURCE](https://fgnt.github.io/python_crashkurs_doc/include/numpy.html)

------------

![](https://bids.berkeley.edu/sites/default/files/styles/400x225/public/projects/numpy_project_page.jpg?itok=flrdydei)


# What is Numpy?
---

NumPy is a general-purpose array-processing package which provides a high-performance, homogenous, multidimensional array object, and tools for working with these arrays.

It is the fundamental package for scientific computing with Python. It contains among other things:
- a powerful N-dimensional array object
- sophisticated (broadcasting) functions
- tools for integrating C/C++ and Fortran code
- useful linear algebra, Fourier transform, and random number capabilities

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data.
Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

-----------

# Python Lists vs. Numpy Arrays
![](https://memegenerator.net/img/instances/400x/74259368.jpg)

- **Size** - Numpy data structures take up less space
    ## Storing List
<img height=500 width=500 src="https://webcourses.ucf.edu/courses/1249560/files/64324060/download?wrap=1">

    ## Storing Array
<img height=500 width=500 src="https://webcourses.ucf.edu/courses/1249560/files/64324040/download?wrap=1">

- **Performance** - they have a need for speed and are faster than lists

- **Functionality** - SciPy and NumPy have optimized functions such as linear algebra operations built-in.

# Installation

```
pip install numpy
```

# Numpy Arrays

---
NumPy’s main object is the homogeneous multidimensional array.
- It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers.
- In NumPy dimensions are called *axes*. The number of axes is *rank*.
- NumPy’s array class is called **ndarray**. It is also known by the alias **array**. 

![](http://community.datacamp.com.s3.amazonaws.com/community/production/ckeditor_assets/pictures/332/content_arrays-axes.png)

![](https://i.stack.imgur.com/gj5ue.jpg)

For example:
```python
[[ 1, 2, 3],
 [ 4, 2, 5]]
```  
This array has:
- rank = 2 (as it is 2-dimensional or it has 2 axes)
- first dimension(axis) length = 2, second dimension has length = 3.
- overall shape can be expressed as: (2, 3)

In [ ]:
# !pip install numpy

In [ ]:
import numpy as np

In [ ]:
list_ = [[1, 2, 3],
       [4, 5, 6],[4,5,6]]
list_

[[1, 2, 3], [4, 5, 6], [4, 5, 6]]

In [ ]:
type(list_)

list

In [ ]:
arr = np.array(list_)

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [4, 5, 6]])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr.dtype

dtype('int32')

In [ ]:
arr.ndim

2

In [ ]:
arr = np.array([1,3])

In [ ]:
arr.ndim

1

In [ ]:
arr = np.array(list_)

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [4, 5, 6]])

In [ ]:
arr.shape

(3, 3)

In [ ]:
ar = np.array([[1,2,3]])
ar

array([[1, 2, 3]])

In [ ]:
ar.ndim

2

In [ ]:
type(ar)

numpy.ndarray

In [ ]:
type(np.array([[1,2,3],[4,5,6]]))

numpy.ndarray

In [ ]:
arr = np.array(list_)

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [4, 5, 6]])

In [ ]:
arr.T # Transpose

array([[1, 4, 4],
       [2, 5, 5],
       [3, 6, 6]])

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [4, 5, 6]])

In [ ]:
arr = arr.T
arr

array([[1, 4, 4],
       [2, 5, 5],
       [3, 6, 6]])

## Array Creation
---
There are various ways to create arrays in NumPy.

- For example, you can create an array from a regular Python **list** or **tuple** using the **array** function. The type of the resulting array is deduced from the type of the elements in the sequences.

In [ ]:
mylist = [[1,2,3],
         [4,5,6]]

In [ ]:
arr = np.array(mylist)

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

- Often, the elements of an array are originally unknown, but its size is known. Hence, NumPy offers several functions to create arrays with **initial placeholder content**. These minimize the necessity of growing arrays, an expensive operation. **For example:** np.zeros, np.ones, np.full, np.empty, np.random.random, np.random.randint etc.

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr = np.zeros((4,4), dtype='int')

In [ ]:
arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
arr.dtype

dtype('int32')

In [ ]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
a = np.full((3,3), 4)
a

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [ ]:
a.ndim

2

In [ ]:
np.random.rand(2,3) # > 0 and < 1

array([[0.6351925 , 0.0395462 , 0.7615884 ],
       [0.66342731, 0.61650664, 0.34412386]])

In [ ]:
np.random.randn()

-0.5107189512838626

In [ ]:
np.random.randint(100) # any one value which is < 100 

51

In [ ]:
np.random.randint(150, size=(2, 4))

array([[ 49,  95,  43, 127],
       [145, 122,   9,  92]])

In [ ]:
np.random.randn(2, 10)

array([[ 0.23729902,  0.60853326, -0.13880599,  1.33321309, -1.39090283,
         0.49175239, -0.42826326,  1.63563417, -1.1047834 ,  0.06752515],
       [-0.02486655,  0.39164238, -1.30033578, -0.82689281, -1.44816779,
        -0.5612042 ,  0.59355662, -1.84480234, -0.9757103 ,  0.53236089]])

In [ ]:
np.random.randn(1)

array([-1.98694079])

In [ ]:
np.random.rand()

0.9971488123657978

- To create sequences of numbers, NumPy provides a function analogous to range that returns arrays instead of lists.
   - **arange:** returns evenly spaced values within a given interval. **step** size is specified.
   - **linspace:** returns evenly spaced values within a given interval. **num** no. of elements are returned.

In [ ]:
range(1,10)

range(1, 10)

In [ ]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
list(range(1,10,3))

[1, 4, 7]

In [ ]:
list(range(1,10,0.5))

TypeError: 'float' object cannot be interpreted as an integer

In [ ]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1,10,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [ ]:
np.arange(1,10,2.55)

array([1.  , 3.55, 6.1 , 8.65])

In [ ]:
np.linspace(5,10,25) # 20 values

array([ 5.        ,  5.20833333,  5.41666667,  5.625     ,  5.83333333,
        6.04166667,  6.25      ,  6.45833333,  6.66666667,  6.875     ,
        7.08333333,  7.29166667,  7.5       ,  7.70833333,  7.91666667,
        8.125     ,  8.33333333,  8.54166667,  8.75      ,  8.95833333,
        9.16666667,  9.375     ,  9.58333333,  9.79166667, 10.        ])

# Array Reshaping
---
We can use **reshape** method to reshape an array. Consider an array with shape (a1, a2, a3, ..., aN). We can reshape and convert it into another array with shape (b1, b2, b3, ....., bM). The only required condition is:   

*a1 x a2 x a3* .... *x aN = b1 x b2 x b3* .... *x bM*

(i.e original size of array remains unchanged.)

In [ ]:
arr = np.array([[1,2,3,4,5,6,7,8]])

In [ ]:
arr.shape

(1, 8)

In [ ]:
arr.ndim

2

In [ ]:
arr

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [ ]:
arr.reshape((2,4))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
arr.reshape((4,2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
arr.reshape((3,3))

ValueError: cannot reshape array of size 8 into shape (3,3)

![](https://i.imgur.com/pwkcvrD.png)

In [ ]:
arr.reshape((4,2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
arr.reshape((4,2), order='C')

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
arr

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [ ]:
arr.reshape((4,2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
arr.reshape((4,2), order='F')

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [ ]:
arr.reshape((2,4), order='F')

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

In [ ]:
arr.reshape((2,4))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# Array Flattening
---
We can use **flatten** method to get a copy of array collapsed into **one dimension**. It accepts *order* argument. Default value is 'C' (for row-major order). Use 'F' for column major order.

In [ ]:
# faltten ---> mean, median, mode, sum, max, min

In [ ]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr.flatten()

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr.sum()

21

In [ ]:
arr.flatten().sum()

21

In [ ]:
arr.flatten()

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr.ravel()

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr.flatten().mean()

3.5

In [ ]:
arr.ravel().mean()

3.5

# Array Indexing
---
Knowing the basics of array indexing is important for analysing and manipulating the array object.
NumPy offers many ways to do array indexing.

- **Positive tuple indexing**


In [ ]:
import numpy as np

In [ ]:
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])

In [ ]:
list_ = [[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]]

In [ ]:
list_[2][1]

0

In [ ]:
list_[2,1]

TypeError: list indices must be integers or slices, not tuple

In [ ]:
arr

array([[-1. ,  2. ,  0. ,  4. ],
       [ 4. , -0.5,  6. ,  0. ],
       [ 2.6,  0. ,  7. ,  8. ],
       [ 3. , -7. ,  4. ,  2. ]])

In [ ]:
arr[2][1]

0.0

In [ ]:
arr[2,1]

0.0

In [ ]:
arr.shape

(4, 4)

In [ ]:
arr

array([[-1. ,  2. ,  0. ,  4. ],
       [ 4. , -0.5,  6. ,  0. ],
       [ 2.6,  0. ,  7. ,  8. ],
       [ 3. , -7. ,  4. ,  2. ]])

In [ ]:
arr[3,4]

IndexError: index 4 is out of bounds for axis 1 with size 4

In [ ]:
arr[2][1]

0.0

![](https://i.imgur.com/fzoXLq1.png)

- **Slicing:** Just like lists in python, NumPy arrays can be sliced. As arrays can be multidimensional, you need to specify a slice for each dimension of the array.

In [ ]:
arr

array([[-1. ,  2. ,  0. ,  4. ],
       [ 4. , -0.5,  6. ,  0. ],
       [ 2.6,  0. ,  7. ,  8. ],
       [ 3. , -7. ,  4. ,  2. ]])

In [ ]:
arr[:2,:2]

array([[-1. ,  2. ],
       [ 4. , -0.5]])

In [ ]:
arr

array([[-1. ,  2. ,  0. ,  4. ],
       [ 4. , -0.5,  6. ,  0. ],
       [ 2.6,  0. ,  7. ,  8. ],
       [ 3. , -7. ,  4. ,  2. ]])

In [ ]:
arr[:,:2]

array([[-1. ,  2. ],
       [ 4. , -0.5],
       [ 2.6,  0. ],
       [ 3. , -7. ]])

In [ ]:
arr

array([[-1. ,  2. ,  0. ,  4. ],
       [ 4. , -0.5,  6. ,  0. ],
       [ 2.6,  0. ,  7. ,  8. ],
       [ 3. , -7. ,  4. ,  2. ]])

In [ ]:
arr[2:,0:2]

array([[ 2.6,  0. ],
       [ 3. , -7. ]])

In [ ]:
arr[2:,2:]

array([[7., 8.],
       [4., 2.]])

In [ ]:
arr[2:, 3:]

array([[8.],
       [2.]])

![](https://i.imgur.com/Tr6SAwv.png)

- **Integer array indexing:** In this method, lists are passed for indexing for each dimension. One to one mapping of corresponding elements is done to construct a new arbitrary array.

In [ ]:
arr[0,0]

-1.0

In [ ]:
arr[1,1]

-0.5

In [ ]:
arr[2,2]

7.0

In [ ]:
arr[3,3]

2.0

In [ ]:
arr

array([[-1. ,  2. ,  0. ,  4. ],
       [ 4. , -0.5,  6. ,  0. ],
       [ 2.6,  0. ,  7. ,  8. ],
       [ 3. , -7. ,  4. ,  2. ]])

In [ ]:
arr[[0,1,2,3], [0,1,2,3]]

array([-1. , -0.5,  7. ,  2. ])

- **Boolean array indexing:** This method is used when we want to pick elements from array which satisfy some condition.

In [ ]:
arr

array([[-1. ,  2. ,  0. ,  4. ],
       [ 4. , -0.5,  6. ,  0. ],
       [ 2.6,  0. ,  7. ,  8. ],
       [ 3. , -7. ,  4. ,  2. ]])

In [ ]:
10 > 20

False

In [ ]:
arr

array([[-1. ,  2. ,  0. ,  4. ],
       [ 4. , -0.5,  6. ,  0. ],
       [ 2.6,  0. ,  7. ,  8. ],
       [ 3. , -7. ,  4. ,  2. ]])

In [ ]:
arr > 0

array([[False,  True, False,  True],
       [ True, False,  True, False],
       [ True, False,  True,  True],
       [ True, False,  True,  True]])

In [ ]:
arr[arr > 0]

array([2. , 4. , 4. , 6. , 2.6, 7. , 8. , 3. , 4. , 2. ])

In [ ]:
arr[0][0]

-1.0

In [ ]:
arr[0][0] > 1

False

In [ ]:
arr[arr < 0]

array([-1. , -0.5, -7. ])

# Array Operations
---
Plethora of built-in arithmetic functions are provided in NumPy.

- **Elementwise operation:** We can use overloaded arithmetic operators to do element-wise operation on array to create a new array. In case of +=, -=, *= operators, the exsisting array is modified.

In [ ]:
import numpy as np

In [ ]:
arr = np.array([[1,2,3],
               [4,5,6]])

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr + 1

array([[2, 3, 4],
       [5, 6, 7]])

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr = arr + 1 # arr +=1

In [ ]:
arr

array([[2, 3, 4],
       [5, 6, 7]])

In [ ]:
arr ** 2

array([[ 4,  9, 16],
       [25, 36, 49]], dtype=int32)

In [ ]:
arr += 1 # arr = arr + 1

In [ ]:
arr

array([[3, 4, 5],
       [6, 7, 8]])

- **Unary operators:** Many unary operations are provided as a method of **ndarray** class. This includes sum, min, max, etc. These functions can also be applied row-wise or column-wise by setting an axis parameter.


In [ ]:
arr = np.array([[1,9,3],[7,6,2]])

In [ ]:
arr

array([[1, 9, 3],
       [7, 6, 2]])

In [ ]:
arr.mean()

4.666666666666667

In [ ]:
arr

array([[1, 9, 3],
       [7, 6, 2]])

In [ ]:
arr.sum()

28

In [ ]:
arr

array([[1, 9, 3],
       [7, 6, 2]])

In [ ]:
arr.sum(axis=0)

array([ 8, 15,  5])

In [ ]:
arr.sum(axis=1)

array([13, 15])

In [ ]:
arr

array([[1, 9, 3],
       [7, 6, 2]])

In [ ]:
arr.min(axis=0)

array([1, 6, 2])

In [ ]:
arr.max(axis = 1)

array([9, 7])

- **Binary operators:** These operations apply on array elementwise and a new array is created. You can use all basic arithmetic operators like +, -, /, *, etc. In case of +=, -=, *= operators, the exsisting array is modified.


In [ ]:
a = np.array([[1,2],
             [3,4]])

b = np.array([[5,6],
             [7,8]])

In [ ]:
c  = a * b
c

array([[ 5, 12],
       [21, 32]])

- **Universal functions (ufunc):** NumPy provides familiar mathematical functions such as sin, cos, exp, etc. These functions also operate elementwise on an array, producing an array as output.

**Note:** All the operations we did above using overloaded operators can be done using ufuncs like np.add, np.subtract, np.multiply, np.divide, np.sum, etc.

In [ ]:
arr

array([[1, 9, 3],
       [7, 6, 2]])

In [ ]:
arr.sum()

28

In [ ]:
a

array([[1, 2],
       [3, 4]])

In [ ]:
b

array([[5, 6],
       [7, 8]])

In [ ]:
np.add(a,b)

array([[ 6,  8],
       [10, 12]])

In [ ]:
np.subtract(a,b)

array([[-4, -4],
       [-4, -4]])

In [ ]:
np.multiply(a,b)

array([[ 5, 12],
       [21, 32]])

In [ ]:
np.sin(arr)

array([[ 0.84147098,  0.41211849,  0.14112001],
       [ 0.6569866 , -0.2794155 ,  0.90929743]])

In [ ]:
arr

array([[1, 9, 3],
       [7, 6, 2]])

In [ ]:
np.cos(arr)

array([[ 0.54030231, -0.91113026, -0.9899925 ],
       [ 0.75390225,  0.96017029, -0.41614684]])

In [ ]:
np.exp(arr)

array([[2.71828183e+00, 8.10308393e+03, 2.00855369e+01],
       [1.09663316e+03, 4.03428793e+02, 7.38905610e+00]])

In [ ]:
np.tan(arr)

array([[ 1.55740772, -0.45231566, -0.14254654],
       [ 0.87144798, -0.29100619, -2.18503986]])

In [ ]:
a = 1.6463

In [ ]:
round(a,2)

1.65

In [ ]:
7 // 4

1

In [ ]:
np.ceil(a)

2.0

In [ ]:
a = 1.64438

In [ ]:
np.ceil(a)

2.0

In [ ]:
a = 1.01

In [ ]:
np.ceil(a)

2.0

In [ ]:
a = 1.0
np.ceil(a)

1.0

In [ ]:
7 / 4

1.75

In [ ]:
7 // 4 #Floor devision

1

# Array Sorting
---
There is a simple **np.sort** method for sorting NumPy arrays.


In [ ]:
a = [1,4,2,4,9,10,2,21,23]

In [ ]:
sorted(a) # temporary change

[1, 2, 2, 4, 4, 9, 10, 21, 23]

In [ ]:
a

[1, 4, 2, 4, 9, 10, 2, 21, 23]

In [ ]:
a.sort() # Permanent change

In [ ]:
a

[1, 2, 2, 4, 4, 9, 10, 21, 23]

In [ ]:
import numpy as np

In [ ]:
arr = np.array([[1, 4, 2],
                [3, 4, 6],
                [0, -1, 5]])

In [ ]:
np.sort(arr, axis=1)

array([[ 1,  2,  4],
       [ 3,  4,  6],
       [-1,  0,  5]])

In [ ]:
arr

array([[ 1,  4,  2],
       [ 3,  4,  6],
       [ 0, -1,  5]])

In [ ]:
np.sort(arr, axis=0)

array([[ 0, -1,  2],
       [ 1,  4,  5],
       [ 3,  4,  6]])

In [ ]:
arr

array([[ 1,  4,  2],
       [ 3,  4,  6],
       [ 0, -1,  5]])

In [ ]:
np.sort(arr,axis = 0)

array([[ 0, -1,  2],
       [ 1,  4,  5],
       [ 3,  4,  6]])

In [ ]:
np.sort(arr, axis=None)

array([-1,  0,  1,  2,  3,  4,  4,  5,  6])

In [ ]:
print(-np.sort(-arr, axis = None))

[ 6  5  4  4  3  2  1  0 -1]


In [ ]:
arr

array([[ 1,  4,  2],
       [ 3,  4,  6],
       [ 0, -1,  5]])

# Array Stacking and Splitting
---
## Stacking

Several arrays can be stacked together along different axes.

- **np.vstack:** To stack arrays along vertical axis.

- **np.hstack:** To stack arrays along horizontal axis.

- **np.column_stack:** To stack 1-D arrays as columns into 2-D arrays.

- **np.row_stack:** To stack 1-D arrays as rows into 2-D arrays.

- **np.concatenate:** To stack arrays along specified axis (axis is passed as argument).

In [ ]:
import numpy as np

In [ ]:
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

c = np.array([[7,8],
             [9,10]])

In [ ]:
a

array([[1, 2],
       [3, 4]])

In [ ]:
b

array([[5, 6],
       [7, 8]])

In [ ]:
# vertical ---> Top to bottom
# Rows ---> Top to bottom
# axis = 0 ---> Top to bottom

# vstack = row_stack = axis 0

# Horizontal ---> left to right
# columns ---> left to right
# axis = 1 ---> left to right

# hstack = column_stack = axis 1

In [ ]:
np.vstack((a,b))# axis = 0
# vstack and row_stack

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
np.row_stack((a,b))# axis = 0

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
np.concatenate((a,b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
np.column_stack((a,b))# axis = 1

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
np.concatenate((a,b), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

## Splitting

For splitting, we have these fuctions:

- **np.hsplit:** Split array along horizontal axis.

- **np.vsplit:** Split array along vertical axis.

- **np.array_split:** Split array along specified axis.

In [ ]:
a = np.array([[1, 3, 5, 7, 9, 11],
              [2, 4, 6, 8, 10, 12]])

In [ ]:
# hsplit = array_split of axis 1
# vsplit = array_split of axis 0

In [ ]:
np.hsplit(a,2)

[array([[1, 3, 5],
        [2, 4, 6]]),
 array([[ 7,  9, 11],
        [ 8, 10, 12]])]

In [ ]:
np.array_split(a, 2, axis=1)# hsplit

[array([[1, 3, 5],
        [2, 4, 6]]),
 array([[ 7,  9, 11],
        [ 8, 10, 12]])]

In [ ]:
np.hsplit(a,3)

[array([[1, 3],
        [2, 4]]),
 array([[5, 7],
        [6, 8]]),
 array([[ 9, 11],
        [10, 12]])]

In [ ]:
a

array([[ 1,  3,  5,  7,  9, 11],
       [ 2,  4,  6,  8, 10, 12]])

In [ ]:
np.hsplit(a,4)

ValueError: array split does not result in an equal division

In [ ]:
a

array([[ 1,  3,  5,  7,  9, 11],
       [ 2,  4,  6,  8, 10, 12]])

In [ ]:
np.vsplit(a,2)

[array([[ 1,  3,  5,  7,  9, 11]]), array([[ 2,  4,  6,  8, 10, 12]])]

In [ ]:
np.vsplit(a,3)

ValueError: array split does not result in an equal division

In [ ]:
np.array_split(a, 2, axis=1)# hsplit

[array([[1, 3, 5],
        [2, 4, 6]]), array([[ 7,  9, 11],
        [ 8, 10, 12]])]

In [ ]:
a

array([[ 1,  3,  5,  7,  9, 11],
       [ 2,  4,  6,  8, 10, 12]])

In [ ]:
np.vsplit(a,2)

[array([[ 1,  3,  5,  7,  9, 11]]), array([[ 2,  4,  6,  8, 10, 12]])]

In [ ]:
np.hsplit(a,3)

[array([[1, 3],
        [2, 4]]), array([[5, 7],
        [6, 8]]), array([[ 9, 11],
        [10, 12]])]